import Foundation
var gate=VoiceTurnGate()
func check(_ value:Bool,_ message:String){if !value{fatalError(message)}}
check(gate.request(),"First instruction starts")
check(!gate.created("a"),"Current response continues")
check(gate.done("a")==true,"Current response completes")
gate.beginTools();check(!gate.request(),"No reply while a tool batch is incomplete")
check(gate.endTools(gate.turn),"Complete batch")
check(gate.drain(),"Exactly one reply after the whole batch")
check(!gate.drain(),"No duplicate reply")
check(!gate.created("b"),"Reply belongs to same turn")
check(gate.done("b")==true,"Reply completes")
check(gate.done("b")==nil,"Duplicate done ignored")
check(gate.request(),"Next instruction starts after prior reply")
let old=gate.turn
check(gate.interrupt(),"Barge in cancels active response")
check(!gate.request(),"Next instruction waits for cancellation acknowledgment")
check(gate.created("c"),"Cancel a response that was still being created")
check(gate.done("c")==false,"Never run cancelled response tools")
check(gate.drain(),"Next instruction starts immediately after cancellation")
check(!gate.endTools(old),"Late tools cannot resume an old turn")
_ = gate.created("d");check(gate.done("b")==nil,"Old done cannot clear new response")
gate.reset();check(gate.request(),"Reset releases stalled turn")
print("PASS: native turn ordering, tool batch, duplicate response, interruption and reset")
