import { StyleSheet } from 'react-native';
export const brand = '#2563EB';
export const themes = {
  dark: {
    bg: '#10151E',
    panel: '#1A2230',
    panel2: '#242E3D',
    line: '#344153',
    text: '#F3F6FC',
    muted: '#A9B6CA',
    accent: '#91BAFF',
    positive: '#89DBAA',
    negative: '#FF9191',
    tint: '#1C2D47',
  },
  light: {
    bg: '#F2F5FA',
    panel: '#FFFFFF',
    panel2: '#E7EDF6',
    line: '#CCD7E6',
    text: '#182337',
    muted: '#53637B',
    accent: '#1D4ED8',
    positive: '#246141',
    negative: '#A32B2B',
    tint: '#E4EDFD',
  },
};
export type Palette = typeof themes.dark;
export const makeStyles = (c: Palette) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: c.bg },
    keyboard: { flex: 1 },
    content: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 24 },
    row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    between: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    grow: { flex: 1 },
    stack: { gap: 12 },
    wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    center: { alignItems: 'center' },
    mt: { marginTop: 18 },
    mb: { marginBottom: 18 },
    text: { color: c.text, fontSize: 14, lineHeight: 21 },
    muted: { color: c.muted, fontSize: 12, lineHeight: 18 },
    tiny: { color: c.muted, fontSize: 10, lineHeight: 15 },
    title: {
      color: c.text,
      fontSize: 29,
      lineHeight: 34,
      fontWeight: '700',
      letterSpacing: -1.1,
    },
    h2: { color: c.text, fontSize: 20, fontWeight: '700', letterSpacing: -0.5 },
    h3: { color: c.text, fontSize: 14, fontWeight: '600' },
    eyebrow: {
      color: c.muted,
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 1.4,
    },
    accent: { color: c.accent },
    positive: { color: c.positive },
    negative: { color: c.negative },
    iconButton: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 24,
    },
    button: {
      minHeight: 49,
      borderRadius: 14,
      paddingHorizontal: 17,
      paddingVertical: 13,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: brand,
    },
    buttonText: { color: '#fff', fontSize: 14, fontWeight: '700' },
    secondary: {
      backgroundColor: c.panel2,
      borderWidth: 1,
      borderColor: c.line,
    },
    secondaryText: { color: c.text },
    disabled: { opacity: 0.45 },
    pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
    link: { minHeight: 44, justifyContent: 'center' },
    linkText: { color: c.accent, fontSize: 12, fontWeight: '600' },
    panel: {
      padding: 16,
      backgroundColor: c.panel,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 18,
    },
    notice: {
      padding: 13,
      borderRadius: 12,
      backgroundColor: c.tint,
      borderWidth: 1,
      borderColor: c.line,
      flexDirection: 'row',
      gap: 9,
      alignItems: 'flex-start',
    },
    noticeText: { flex: 1, color: c.muted, fontSize: 12, lineHeight: 18 },
    pill: {
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 6,
      backgroundColor: c.panel2,
      alignSelf: 'flex-start',
    },
    pillText: {
      color: c.muted,
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
    livePill: { backgroundColor: '#153968' },
    livePillText: { color: '#A1C5FF' },
    rule: { height: 1, backgroundColor: c.line, marginVertical: 16 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
      paddingHorizontal: 19,
      paddingVertical: 6,
      minHeight: 64,
    },
    wordmark: {
      color: c.text,
      fontSize: 21,
      fontWeight: '900',
      letterSpacing: -1,
    },
    brandSlash: { color: brand, fontWeight: '900' },
    brandSub: { color: c.muted, fontSize: 6, letterSpacing: 1.6, marginTop: 4 },
    walletMini: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      minHeight: 44,
      borderRadius: 22,
      paddingHorizontal: 8,
      backgroundColor: c.panel2,
    },
    walletText: { color: c.text, fontSize: 10, fontWeight: '700' },
    plus: {
      width: 23,
      height: 23,
      borderRadius: 12,
      backgroundColor: brand,
      alignItems: 'center',
      justifyContent: 'center',
    },
    greeting: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 6,
      marginBottom: 17,
    },
    greetingTitle: {
      color: c.text,
      fontSize: 27,
      fontWeight: '700',
      letterSpacing: -1,
      marginTop: 7,
    },
    homeActions: { flexDirection: 'row', gap: 5 },
    themeButton: {
      backgroundColor: c.panel2,
      borderWidth: 1,
      borderColor: c.line,
    },
    voiceButton: {
      borderWidth: 1,
      borderColor: '#2563EB88',
      backgroundColor: '#2563eb09',
    },
    sportList: { gap: 15, paddingBottom: 12, paddingTop: 2 },
    sportItem: { width: 62, alignItems: 'center', gap: 7 },
    sportCircle: {
      height: 45,
      width: 45,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 25,
      backgroundColor: c.panel,
      borderWidth: 1,
      borderColor: c.line,
    },
    sportLabel: { fontSize: 10, color: c.muted },
    selectedCircle: { backgroundColor: brand, borderColor: brand },
    segments: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderColor: c.line,
      gap: 25,
      marginBottom: 18,
    },
    segment: {
      minHeight: 47,
      justifyContent: 'center',
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    segmentActive: { borderBottomColor: brand },
    segmentText: { fontSize: 12, color: c.muted },
    segmentTextActive: { color: c.text, fontWeight: '700' },
    feature: {
      padding: 15,
      borderRadius: 21,
      backgroundColor: '#1B2E49',
      borderWidth: 1,
      borderColor: '#3A5273',
      overflow: 'hidden',
    },
    featureText: { color: '#B8C9DF', fontSize: 10 },
    scoreboard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 17,
      gap: 5,
    },
    teamBlock: { flex: 1, alignItems: 'center' },
    crest: {
      height: 48,
      width: 43,
      borderRadius: 9,
      borderBottomLeftRadius: 18,
      borderBottomRightRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    teamName: {
      color: '#F3F6FC',
      fontSize: 11,
      fontWeight: '600',
      textAlign: 'center',
      marginTop: 9,
      lineHeight: 16,
    },
    scoreCenter: { width: 106, alignItems: 'center' },
    score: {
      color: '#F3F6FC',
      fontSize: 35,
      fontWeight: '700',
      letterSpacing: 1,
    },
    scoreStage: {
      color: '#A2C6FF',
      fontSize: 10,
      textAlign: 'center',
      marginTop: 5,
      lineHeight: 15,
    },
    featureFoot: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 8,
    },
    pitch: {
      position: 'absolute',
      right: -60,
      bottom: -20,
      width: 300,
      height: 220,
      opacity: 0.1,
      transform: [{ rotate: '-16deg' }],
    },
    oddsRow: { flexDirection: 'row', gap: 7, marginTop: 12 },
    odd: {
      flex: 1,
      minHeight: 46,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 10,
      paddingHorizontal: 9,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 4,
      backgroundColor: c.panel2,
    },
    featureOdd: { backgroundColor: '#ffffff08', borderColor: '#425572' },
    oddSelected: { backgroundColor: brand, borderColor: brand },
    oddLabel: { fontSize: 10, color: c.muted, flexShrink: 1 },
    oddNumber: { fontSize: 13, fontWeight: '700', color: c.text },
    white: { color: '#fff' },
    movement: {
      position: 'absolute',
      right: 4,
      top: 1,
      fontSize: 8,
      color: c.positive,
    },
    section: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 22,
      marginBottom: 12,
      minHeight: 30,
    },
    league: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginBottom: 9,
    },
    leagueText: { fontSize: 10, color: c.muted, flex: 1, lineHeight: 15 },
    match: {
      backgroundColor: c.panel,
      borderColor: c.line,
      borderWidth: 1,
      padding: 13,
      borderRadius: 16,
      marginBottom: 13,
    },
    matchMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 3,
    },
    matchMetaText: { fontSize: 10, color: c.accent },
    matchTeam: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 29,
    },
    teamDot: {
      width: 23,
      height: 23,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
    },
    teamInitial: { fontSize: 8, fontWeight: '800', color: '#19273B' },
    teamRowName: { flex: 1, fontSize: 12, fontWeight: '500', color: c.text },
    teamScore: { fontSize: 16, color: c.text, fontWeight: '700' },
    matchFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 3,
    },
    matchMarket: { fontSize: 10, color: c.muted },
    arenaBanner: {
      backgroundColor: c.tint,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 16,
      padding: 15,
      marginTop: 18,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    arenaEmblem: {
      height: 43,
      width: 43,
      borderRadius: 13,
      backgroundColor: '#2563eb18',
      alignItems: 'center',
      justifyContent: 'center',
    },
    footer: {
      minHeight: 60,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingTop: 14,
    },
    age: {
      height: 23,
      width: 23,
      borderWidth: 1,
      borderColor: c.muted,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    ageText: { fontSize: 8, color: c.muted },
    footerText: { fontSize: 9, color: c.muted, textAlign: 'center' },
    nav: {
      flexDirection: 'row',
      borderTopWidth: 1,
      borderColor: c.line,
      paddingTop: 7,
      paddingHorizontal: 7,
      backgroundColor: c.bg,
    },
    navItem: {
      flex: 1,
      minHeight: 51,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 5,
    },
    navLabel: { fontSize: 10, color: c.muted },
    navIndicator: {
      position: 'absolute',
      top: -8,
      width: 18,
      height: 3,
      borderRadius: 2,
      backgroundColor: brand,
    },
    dock: { paddingHorizontal: 18, paddingVertical: 8, backgroundColor: c.bg },
    dockButton: {
      minHeight: 47,
      borderRadius: 13,
      paddingHorizontal: 13,
      backgroundColor: brand,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    dockCount: {
      width: 25,
      height: 25,
      borderRadius: 7,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    dockText: { fontSize: 13, fontWeight: '700', color: '#fff' },
    pageHead: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginBottom: 17,
      marginLeft: -9,
    },
    pageHeadTitle: {
      flex: 1,
      fontSize: 24,
      fontWeight: '700',
      letterSpacing: -0.6,
      color: c.text,
    },
    search: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      paddingHorizontal: 13,
      minHeight: 49,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 13,
      backgroundColor: c.panel,
    },
    searchInput: {
      flex: 1,
      minWidth: 0,
      color: c.text,
      fontSize: 14,
      paddingVertical: 12,
    },
    input: {
      minHeight: 51,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 12,
      backgroundColor: c.panel2,
      color: c.text,
      fontSize: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    label: { fontSize: 12, color: c.text, marginBottom: 8, marginTop: 16 },
    passwordWrap: { position: 'relative' },
    passwordInput: { paddingRight: 51 },
    passwordEye: { position: 'absolute', right: 4, top: 4 },
    checkRow: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
    },
    check: {
      width: 20,
      height: 20,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: c.line,
      justifyContent: 'center',
      alignItems: 'center',
    },
    grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 11 },
    directoryCard: {
      width: '48%',
      minHeight: 124,
      backgroundColor: c.panel,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 17,
      padding: 16,
      gap: 10,
    },
    chipRow: { gap: 7, paddingVertical: 12 },
    chip: {
      minHeight: 44,
      paddingHorizontal: 13,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 23,
      borderWidth: 1,
      borderColor: c.line,
      backgroundColor: c.panel,
    },
    chipText: { fontSize: 11, color: c.text },
    activeChip: { backgroundColor: brand, borderColor: brand },
    calendar: {
      width: 47,
      height: 65,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: c.line,
      backgroundColor: c.panel,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
    },
    market: {
      borderRadius: 15,
      borderWidth: 1,
      borderColor: c.line,
      paddingHorizontal: 13,
      paddingBottom: 13,
      backgroundColor: c.panel,
      marginBottom: 10,
    },
    marketHeader: {
      minHeight: 49,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    momentum: {
      height: 45,
      flexDirection: 'row',
      gap: 3,
      alignItems: 'flex-end',
      marginTop: 13,
    },
    momentBar: { flex: 1, borderTopLeftRadius: 2, borderTopRightRadius: 2 },
    stat: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 16,
      marginBottom: 8,
    },
    statBars: { flexDirection: 'row', gap: 4, height: 4 },
    modalBackdrop: {
      flex: 1,
      backgroundColor: '#00000099',
      justifyContent: 'flex-end',
    },
    modalShade: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0 },
    sheet: {
      maxHeight: '92%',
      backgroundColor: c.bg,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderWidth: 1,
      borderColor: c.line,
      paddingTop: 9,
    },
    sheetScroll: { paddingHorizontal: 20, paddingBottom: 32 },
    handle: {
      height: 4,
      width: 34,
      borderRadius: 2,
      backgroundColor: c.muted,
      alignSelf: 'center',
      marginBottom: 9,
    },
    sheetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      marginBottom: 10,
    },
    sheetTitle: {
      flex: 1,
      color: c.text,
      fontSize: 21,
      fontWeight: '700',
      letterSpacing: -0.6,
    },
    slipTabs: {
      flexDirection: 'row',
      backgroundColor: c.panel,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.line,
      padding: 4,
      marginBottom: 8,
    },
    slipTab: {
      flex: 1,
      minHeight: 40,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    slipTabActive: { backgroundColor: c.panel2 },
    slipItem: {
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderColor: c.line,
    },
    selectionCheck: {
      height: 26,
      width: 26,
      borderRadius: 7,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.tint,
    },
    stakeInput: { fontSize: 27, fontWeight: '700' },
    quickStakes: {
      flexDirection: 'row',
      gap: 7,
      marginTop: 9,
      marginBottom: 16,
    },
    quickStake: {
      flex: 1,
      minHeight: 44,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 10,
      backgroundColor: c.panel,
      alignItems: 'center',
      justifyContent: 'center',
    },
    calcLine: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 10,
      marginVertical: 6,
    },
    calcReturn: {
      borderTopWidth: 1,
      borderColor: c.line,
      marginTop: 12,
      paddingTop: 15,
      paddingBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    returnNumber: {
      fontSize: 25,
      fontWeight: '700',
      color: c.accent,
      letterSpacing: -0.7,
    },
    error: {
      fontSize: 12,
      color: c.negative,
      lineHeight: 18,
      marginVertical: 10,
    },
    toast: {
      position: 'absolute',
      left: 18,
      right: 18,
      bottom: 112,
      padding: 14,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 14,
      backgroundColor: c.tint,
      flexDirection: 'row',
      gap: 8,
      alignItems: 'center',
      zIndex: 99,
      elevation: 10,
    },
    toastText: { color: c.text, fontSize: 12, lineHeight: 18, flex: 1 },
    empty: { paddingVertical: 38, alignItems: 'center', gap: 12 },
    successIcon: {
      height: 79,
      width: 79,
      borderRadius: 40,
      backgroundColor: c.tint,
      borderWidth: 1,
      borderColor: c.line,
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: 23,
    },
    casinoFeature: {
      padding: 23,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: '#534163',
      backgroundColor: '#2C223B',
      minHeight: 238,
      overflow: 'hidden',
    },
    casinoTitle: {
      fontSize: 31,
      color: '#fff',
      fontWeight: '700',
      letterSpacing: -1.1,
      lineHeight: 35,
      marginTop: 17,
    },
    casinoCopy: {
      fontSize: 12,
      lineHeight: 19,
      color: '#C4B4D4',
      marginTop: 9,
      maxWidth: 190,
    },
    diceArt: {
      position: 'absolute',
      right: 25,
      top: 72,
      height: 90,
      width: 90,
      borderRadius: 22,
      backgroundColor: '#86B5FF',
      alignItems: 'center',
      justifyContent: 'center',
      transform: [{ rotate: '15deg' }],
      shadowColor: '#4474BC',
      shadowOffset: { width: 9, height: 10 },
      shadowOpacity: 1,
      shadowRadius: 0,
    },
    gameCard: {
      backgroundColor: c.panel,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 16,
      padding: 13,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      marginBottom: 12,
    },
    gameThumb: {
      width: 72,
      height: 75,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#263E61',
    },
    gameStage: {
      height: 238,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 20,
      backgroundColor: c.panel,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 15,
      marginVertical: 17,
    },
    gameSymbol: { fontSize: 88, color: c.accent },
    multiplier: { fontSize: 55, fontWeight: '700', color: c.accent },
    playingCard: {
      height: 136,
      width: 99,
      borderRadius: 14,
      borderWidth: 5,
      borderColor: '#B8CEE9',
      backgroundColor: '#F5F8FC',
      alignItems: 'center',
      justifyContent: 'center',
    },
    playingCardText: { fontSize: 36, color: '#203B67' },
    avatar: {
      width: 39,
      height: 39,
      borderRadius: 20,
      backgroundColor: c.tint,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: { color: c.accent, fontSize: 12, fontWeight: '700' },
    communityCard: {
      padding: 16,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: c.line,
      backgroundColor: c.panel,
      marginBottom: 13,
    },
    communitySelection: {
      flexDirection: 'row',
      gap: 8,
      paddingTop: 13,
      paddingBottom: 3,
    },
    communityStats: {
      flexDirection: 'row',
      borderTopWidth: 1,
      borderColor: c.line,
      marginTop: 16,
      paddingTop: 13,
      paddingBottom: 16,
    },
    formCell: {
      width: 16,
      height: 19,
      borderRadius: 3,
      backgroundColor: '#89dbaa15',
      alignItems: 'center',
      justifyContent: 'center',
    },
    menuGroup: {
      backgroundColor: c.panel,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 16,
      overflow: 'hidden',
      marginTop: 9,
      marginBottom: 22,
    },
    menuItem: {
      minHeight: 55,
      paddingHorizontal: 15,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: c.line,
    },
    menuText: { flex: 1, color: c.text, fontSize: 13 },
    walletCard: {
      backgroundColor: '#1B2E49',
      borderWidth: 1,
      borderColor: '#3A5273',
      borderRadius: 20,
      padding: 23,
      marginVertical: 16,
    },
    walletBalance: {
      fontSize: 37,
      color: '#fff',
      fontWeight: '700',
      letterSpacing: -1.2,
      marginTop: 12,
      marginBottom: 22,
    },
    settingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 18,
      paddingVertical: 17,
      borderBottomWidth: 1,
      borderColor: c.line,
    },
    welcome: { alignItems: 'center', paddingTop: 24 },
    welcomeArt: {
      height: 218,
      width: 218,
      borderRadius: 110,
      borderWidth: 1,
      borderColor: '#426CAF',
      backgroundColor: '#2563eb0b',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 15,
      marginBottom: 24,
    },
    welcomeTitle: {
      color: c.text,
      fontSize: 36,
      lineHeight: 40,
      fontWeight: '700',
      letterSpacing: -1.4,
      textAlign: 'center',
    },
    welcomeCopy: {
      fontSize: 14,
      color: c.muted,
      lineHeight: 22,
      textAlign: 'center',
      marginTop: 16,
      marginBottom: 24,
      maxWidth: 300,
    },
    welcomeDots: { flexDirection: 'row', gap: 6, marginBottom: 23 },
    welcomeDot: {
      height: 5,
      width: 5,
      borderRadius: 3,
      backgroundColor: c.line,
    },
    welcomeDotActive: { width: 23, backgroundColor: brand },
  });
